### ISSUE TITLE
CC API integration

### ISSUE THREAD

**Issue by einsweniger** [rootzoll/ccstamper#1]
Creative Commons provides multilingual access to their license texts through an [API](https://api.creativecommons.org/docs/readme_15.html). This might be better than selecting the license text through their front end DOM.

**Comment by rootzoll** [comment]
Thanks, good idea. I will keep the issue open for next implementation sprint.

**Comment by rootzoll** [comment]
I got the time to look a bit deeper what would be the best way to add CC license information to image metadata. Thanks for the link to the API again, it pushed me into the right direction. Best and most up to date way seems to follow the proposal from Matt Lee and Rob Myers:

**Proposal for a formal way of expressing public license information in Exif**
https://github.com/creativecommons/exif
